# Generated by Django 4.2.21 on 2025-05-15 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_initial_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='area_of_activity',
            field=models.CharField(blank=True, help_text='Ex: Música, Dança, Artes Visuais…', max_length=200, verbose_name='Área de Atuação'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, help_text='Conte aqui um breve histórico ou currículo resumido.', verbose_name='Biografia / Descrição'),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact',
            field=models.CharField(blank=True, help_text='Telefone, WhatsApp ou outra forma de contato.', max_length=100, verbose_name='Telefone / Contato'),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='education',
            field=models.CharField(blank=True, help_text='Ex: Bacharel em Música, Técnico em Teatro…', max_length=200, verbose_name='Formação Cultural'),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
