# Generated by Django 4.2.21 on 2025-05-15 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_area_of_activity_agent_bio_agent_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='space',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='space',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='space',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='space',
            name='location',
            field=models.CharField(help_text='Coordenadas em "lat,lng" ou descrição do local', max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
