# Generated by Django 4.2.21 on 2025-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_created_at_remove_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='portfolio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='portfolios/'),
        ),
    ]
