# Generated by Django 4.2.21 on 2025-05-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agent_portfolio_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='agents/photos/', verbose_name='Foto do agente'),
        ),
    ]
